### ISSUE TITLE
to put number rhyme prompts in with the code

### ISSUE THREAD

**Issue by andrew-jolley** [BingoCaller2020/bingocaller#3]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
it would be good if the number also had the bingo rhyme with it

**Describe alternatives you've considered**
having my own number rhymes on paper

**Additional context**

**Comment by BingoCaller2020** [comment]
At the moment this wouldn't be possible but we will keep this in archive and will start this as soon as possible.
Thanks!
